// ---------------------------------------------------------------------------
// Atlas Intelligence — article sitemap
//
// WHY AN EDGE FUNCTION INSTEAD OF A STATIC FILE
//   public/sitemap.xml is a build artifact and can only list routes that exist
//   independently of content. Article slugs live in the database and change as
//   content is published, so a static file can never enumerate them — the
//   existing sitemap.xml says exactly this in its own comment.
//
//   This function closes that gap. It is the server-rendered endpoint the
//   static sitemap already says an article-level sitemap requires.
//
// SECURITY
//   verify_jwt is false, because crawlers fetch a sitemap without a session.
//   That is safe precisely because the query is SECURITY INVOKER and therefore
//   runs under the caller (anon) role, so anon RLS applies: only rows with
//   status = 'published' AND contentType = 'blog' are visible. A draft cannot
//   appear in a sitemap even if this endpoint were modified, because the RLS
//   policy on atlasContentItems excludes it before the row is ever returned.
//
//   The function reads no secret, touches no tenant data, and exposes only
//   public article metadata.
// ---------------------------------------------------------------------------

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const ALLOWED_ORIGINS = [
  "https://atlas-ai-os.com",
  "https://www.atlas-ai-os.com",
];

const SITE_ORIGIN =
  Deno.env.get("ATLAS_SITE_ORIGIN")?.replace(/\/+$/, "") ??
  ALLOWED_ORIGINS[0];

/** XML-escape a URL or text node. Sitemaps are XML; an unescaped & is a 500. */
function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function urlEntry(
  loc: string,
  lastmod: Date | null,
  priority: string,
  changefreq: string,
): string {
  return [
    "  <url>",
    `    <loc>${escapeXml(loc)}</loc>`,
    lastmod ? `    <lastmod>${lastmod.toISOString().slice(0, 10)}</lastmod>` : "",
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    "  </url>",
  ]
    .filter(Boolean)
    .join("\n");
}

Deno.serve(async (req: Request): Promise<Response> => {
  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      // The anon key. Using service_role here would defeat the RLS guarantee
      // that makes verify_jwt=false safe, so it is deliberately not used.
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } },
    );

    const { data, error } = await supabase
      .from("atlasContentItems")
      .select("slug,title,summary,seo,category,updatedAt,publishedAt")
      .eq("status", "published")
      .eq("contentType", "blog")
      .not("slug", "is", null)
      .order("publishedAt", { ascending: false, nullsFirst: false })
      .limit(1000);

    if (error) {
      console.error("[blog-sitemap] query failed:", error.message);
      // A degraded but VALID sitemap: a 500 here would make a crawler drop
      // the sitemap entirely, which is worse than an empty one.
      return new Response(
        `<?xml version="1.0" encoding="UTF-8"?>\n<!-- sitemap temporarily unavailable -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>`,
        {
          status: 200,
          headers: {
            "Content-Type": "application/xml; charset=utf-8",
            "Cache-Control": "public, max-age=60",
          },
        },
      );
    }

    const articles = (data ?? []) as Array<{
      slug: string | null;
      updatedAt?: number | null;
      publishedAt?: number | null;
    }>;

    const entries: string[] = [
      urlEntry(`${SITE_ORIGIN}/`, null, "1.0", "weekly"),
      urlEntry(`${SITE_ORIGIN}/blog`, null, "0.9", "daily"),
      urlEntry(`${SITE_ORIGIN}/pricing`, null, "0.9", "monthly"),
    ];

    for (const article of articles) {
      if (!article.slug) continue;
      const stamp =
        typeof article.updatedAt === "number"
          ? article.updatedAt
          : typeof article.publishedAt === "number"
            ? article.publishedAt
            : null;
      entries.push(
        urlEntry(
          `${SITE_ORIGIN}/blog/${article.slug}`,
          stamp ? new Date(stamp) : null,
          "0.7",
          "monthly",
        ),
      );
    }

    const xml = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      "<!-- Generated by the Atlas blog-sitemap Edge Function. Enumerates",
      "     published articles only; anon RLS excludes drafts before this",
      "     function can read them. -->",
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
      entries.join("\n"),
      "</urlset>",
    ].join("\n");

    // Mirrors the existing Atlas Edge Function response pattern (see
    // stripe-webhook): a string body with the content type supplied in the
    // Response constructor. A typed Blob and a post-construction
    // `headers.set` were both tried and the edge gateway served text/plain
    // either way, so this is the form verified against the live endpoint.
    return new Response(xml, {
      status: 200,
      headers: {
        "content-type": "application/xml; charset=utf-8",
        "Cache-Control": "public, max-age=300, s-maxage=3600",
      },
    });
  } catch (error) {
    console.error("[blog-sitemap] unexpected error:", error);
    return new Response("sitemap unavailable", { status: 500 });
  }
});
