// ---------------------------------------------------------------------------
// Atlas — deterministic thumbnail compositor (pure module)
//
// WHAT THIS IS
//   A pure, dependency-free module that turns an APPROVED text string plus a
//   supplied raster background into a complete, standalone SVG document. It
//   validates the request, escapes the text as XML DATA, embeds the background
//   as a data URI, and computes every layout value deterministically. It does
//   NOT rasterize (that is raster.ts), does NOT generate or rewrite copy, and
//   does NOT touch the network, the database, or storage.
//
// THE EXACT-TEXT GUARANTEE
//   Approved text enters as structured data (`text.lines`) and leaves as escaped
//   SVG `<text>` elements. Nothing rewrites, summarizes, shortens or invents it,
//   and no model renders it. The only transformation is lossless XML escaping
//   (`&`, `<`, `>`, `"`, `'`), which decodes back to the original string, so the
//   string that ships is the string that was approved.
//
// WHY THE LAYOUT IS COMPUTED, NOT CONFIGURED PER CALL
//   A thumbnail must be legible and predictable. Font size is derived from the
//   canvas, the line count and a conservative advance-width estimate, so any
//   approved line fits without the caller having to reason about font metrics.
//   Explicit overrides are accepted but bounded. There is no randomness, no
//   wall-clock, no locale-dependent formatting and no `Math.random` anywhere:
//   identical input yields a byte-identical SVG.
// ---------------------------------------------------------------------------

import { decodeBase64ToBytes } from "./base64.ts";

/** The renderer identity. A deterministic artifact can only be regenerated by
 *  the exact renderer + font + layout that produced it, so the version travels
 *  with every result. */
export const COMPOSITOR_VERSION = "thumbnail-compositor-v1";

/** The one supported output geometry. 16:9 exactly. */
export const TARGET_WIDTH = 2048;
export const TARGET_HEIGHT = 1152;
export const TARGET_ASPECT_RATIO = "16:9";

/** Matches the public `blog-media` bucket limit, so an accepted background is
 *  always one Atlas can also store. */
export const MAX_BACKGROUND_BYTES = 2 * 1024 * 1024;
/** Bound the base64 text before decoding: `ceil(bytes/3)*4` plus the prefix. */
export const MAX_BACKGROUND_DATA_URI_CHARS =
  Math.ceil(MAX_BACKGROUND_BYTES / 3) * 4 + 64;
/** Whole-request ceiling, enforced from Content-Length and from the parsed body. */
export const MAX_REQUEST_BYTES = MAX_BACKGROUND_DATA_URI_CHARS + 64 * 1024;

/** Text bounds. A thumbnail overlay is a short headline, not a paragraph. */
export const MAX_TEXT_LINES = 6;
export const MAX_LINE_CHARS = 120;

// Deterministic layout constants. Changing any of these changes the rendered
// bytes for a given input, so they are part of the compositor version's
// contract and are asserted by the determinism test.
const DEFAULT_PADDING_RATIO = 0.055;
const DEFAULT_LINE_HEIGHT = 1.12;
const MAX_FONT_SIZE_RATIO = 0.15;
/** Conservative uppercase advance width (em) for the embedded bold face. */
const ADVANCE_WIDTH_RATIO = 0.66;
const TEXT_FILL = "#f8fafc";

// ---------------------------------------------------------------------------
// Error model — explicit, deterministic, machine-readable, secret-free
// ---------------------------------------------------------------------------

export const COMPOSITOR_ERROR = {
  MALFORMED_REQUEST: "MALFORMED_REQUEST",
  MISSING_BACKGROUND: "MISSING_BACKGROUND",
  INVALID_BACKGROUND_DATA_URI: "INVALID_BACKGROUND_DATA_URI",
  UNSUPPORTED_BACKGROUND_TYPE: "UNSUPPORTED_BACKGROUND_TYPE",
  BACKGROUND_TOO_LARGE: "BACKGROUND_TOO_LARGE",
  INVALID_BACKGROUND_IMAGE: "INVALID_BACKGROUND_IMAGE",
  MISSING_TEXT: "MISSING_TEXT",
  EMPTY_TEXT: "EMPTY_TEXT",
  TOO_MANY_LINES: "TOO_MANY_LINES",
  TEXT_LINE_TOO_LONG: "TEXT_LINE_TOO_LONG",
  INVALID_TEXT_CHARACTERS: "INVALID_TEXT_CHARACTERS",
  INVALID_DIMENSIONS: "INVALID_DIMENSIONS",
  UNSUPPORTED_DIMENSIONS: "UNSUPPORTED_DIMENSIONS",
  INVALID_LAYOUT: "INVALID_LAYOUT",
  RASTERIZATION_FAILED: "RASTERIZATION_FAILED",
} as const;

export type CompositorErrorCode =
  (typeof COMPOSITOR_ERROR)[keyof typeof COMPOSITOR_ERROR];

export interface CompositorFailure {
  ok: false;
  code: CompositorErrorCode;
  message: string;
}

// ---------------------------------------------------------------------------
// Contract
// ---------------------------------------------------------------------------

export type TextAlignment = "upper-left" | "upper-right";

export interface ThumbnailComposeRequest {
  background: { dataUri: string };
  text: { lines: string[] };
  layout: {
    width: number;
    height: number;
    paddingPx?: number;
    fontSizePx?: number;
    lineHeight?: number;
    align?: TextAlignment;
  };
  metadata?: {
    contentPackageId?: string;
    compositorVersion?: string;
  };
}

export interface ResolvedLayout {
  width: number;
  height: number;
  paddingPx: number;
  fontSizePx: number;
  lineHeight: number;
  align: TextAlignment;
}

export interface ThumbnailComposeInput {
  /** The validated, canonical PNG data URI, embedded verbatim. */
  backgroundDataUri: string;
  backgroundBytes: Uint8Array;
  lines: string[];
  layout: ResolvedLayout;
  contentPackageId: string | null;
}

export type ComposeValidation =
  | { ok: true; input: ThumbnailComposeInput }
  | CompositorFailure;

// ---------------------------------------------------------------------------
// XML escaping
// ---------------------------------------------------------------------------

const XML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&apos;",
};

/**
 * Escape a string for use as XML TEXT CONTENT.
 *
 * `&` must be replaced first (a single pass over the alternation avoids the
 * double-escaping bug). The result decodes back to the exact original string,
 * so escaping is lossless: the approved text is preserved byte-for-byte at the
 * data level.
 */
export function escapeXmlText(value: string): string {
  return value.replace(/[&<>"']/g, (char) => XML_ESCAPES[char]);
}

// XML 1.0 forbids most C0 control characters outright. They are rejected rather
// than stripped, because silently altering approved text would break the
// exact-text guarantee.
/* eslint-disable no-control-regex -- XML forbids these control characters; detecting them is the point. */
const DISALLOWED_CONTROL_CHARS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/;
/* eslint-enable no-control-regex */

// ---------------------------------------------------------------------------
// Background validation
// ---------------------------------------------------------------------------

const PNG_PREFIX = "data:image/png;base64,";
const PNG_DATA_URI_PATTERN = /^data:image\/png;base64,([A-Za-z0-9+/]+={0,2})$/;
const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

function isPng(bytes: Uint8Array): boolean {
  if (bytes.length < PNG_SIGNATURE.length) return false;
  return PNG_SIGNATURE.every((byte, index) => bytes[index] === byte);
}

/**
 * Validate and decode a background data URI.
 *
 * ONLY a PNG data URI is accepted, and only base64 characters are permitted
 * after the prefix — which means the value cannot carry a quote, a `<`, a `>`,
 * a newline, or any other XML-sensitive character into the SVG. The bytes are
 * decoded solely to prove they are a real PNG; the ORIGINAL, canonical string is
 * what gets embedded, so the background is never re-rendered or reinterpreted.
 */
export function decodeBackground(
  dataUri: unknown,
): { ok: true; dataUri: string; bytes: Uint8Array } | CompositorFailure {
  if (typeof dataUri !== "string") {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.MISSING_BACKGROUND,
      message: "A background PNG data URI is required.",
    };
  }
  if (dataUri.length === 0) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.MISSING_BACKGROUND,
      message: "The background data is empty.",
    };
  }
  if (dataUri.length > MAX_BACKGROUND_DATA_URI_CHARS) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.BACKGROUND_TOO_LARGE,
      message: `The background exceeds the ${MAX_BACKGROUND_BYTES}-byte limit.`,
    };
  }
  if (!dataUri.startsWith("data:")) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_BACKGROUND_DATA_URI,
      message: "The background must be supplied as a base64 data URI.",
    };
  }
  if (!dataUri.startsWith(PNG_PREFIX)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.UNSUPPORTED_BACKGROUND_TYPE,
      message: "The background must be a PNG data URI (data:image/png;base64,…).",
    };
  }
  const match = PNG_DATA_URI_PATTERN.exec(dataUri);
  if (!match) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_BACKGROUND_DATA_URI,
      message: "The background data URI is not valid base64.",
    };
  }
  let bytes: Uint8Array;
  try {
    bytes = decodeBase64ToBytes(match[1]);
  } catch {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_BACKGROUND_DATA_URI,
      message: "The background data URI could not be decoded.",
    };
  }
  if (!isPng(bytes)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_BACKGROUND_IMAGE,
      message: "The background is not a valid PNG image.",
    };
  }
  return { ok: true, dataUri, bytes };
}

// ---------------------------------------------------------------------------
// Text validation
// ---------------------------------------------------------------------------

export function validateTextLines(
  lines: unknown,
): { ok: true; lines: string[] } | CompositorFailure {
  if (!Array.isArray(lines) || lines.length === 0) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.MISSING_TEXT,
      message: "At least one line of overlay text is required.",
    };
  }
  if (lines.length > MAX_TEXT_LINES) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.TOO_MANY_LINES,
      message: `At most ${MAX_TEXT_LINES} lines of overlay text are supported.`,
    };
  }
  const out: string[] = [];
  for (const raw of lines) {
    if (typeof raw !== "string") {
      return {
        ok: false,
        code: COMPOSITOR_ERROR.MALFORMED_REQUEST,
        message: "Every overlay text line must be a string.",
      };
    }
    if (raw.trim().length === 0) {
      return {
        ok: false,
        code: COMPOSITOR_ERROR.EMPTY_TEXT,
        message: "Overlay text lines must not be empty.",
      };
    }
    if (raw.length > MAX_LINE_CHARS) {
      return {
        ok: false,
        code: COMPOSITOR_ERROR.TEXT_LINE_TOO_LONG,
        message: `Overlay text lines may not exceed ${MAX_LINE_CHARS} characters.`,
      };
    }
    if (DISALLOWED_CONTROL_CHARS.test(raw)) {
      return {
        ok: false,
        code: COMPOSITOR_ERROR.INVALID_TEXT_CHARACTERS,
        message: "Overlay text contains characters that are not valid in XML.",
      };
    }
    out.push(raw);
  }
  return { ok: true, lines: out };
}

// ---------------------------------------------------------------------------
// Layout resolution
// ---------------------------------------------------------------------------

function isPositiveFinite(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value > 0;
}

/**
 * Resolve the layout deterministically.
 *
 * `width`/`height` default to the target and, when supplied, MUST equal it: the
 * compositor has exactly one supported geometry, and silently letterboxing a
 * different request would produce a thumbnail whose dimensions no consumer
 * expects. Font size is the minimum of three deterministic bounds — a fraction
 * of the canvas, the vertical budget for the line count, and the horizontal
 * budget implied by the widest line — so approved text is always on-canvas.
 */
export function resolveLayout(raw: unknown): { ok: true; layout: ResolvedLayout } | CompositorFailure {
  const layout = (raw ?? {}) as Record<string, unknown>;

  const width = layout["width"] === undefined ? TARGET_WIDTH : layout["width"];
  const height = layout["height"] === undefined ? TARGET_HEIGHT : layout["height"];

  if (!isPositiveFinite(width) || !isPositiveFinite(height)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_DIMENSIONS,
      message: "Layout width and height must be positive numbers.",
    };
  }
  if (width !== TARGET_WIDTH || height !== TARGET_HEIGHT) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.UNSUPPORTED_DIMENSIONS,
      message: `The compositor only renders ${TARGET_WIDTH}x${TARGET_HEIGHT} (${TARGET_ASPECT_RATIO}).`,
    };
  }

  const align = layout["align"] === undefined ? "upper-left" : layout["align"];
  if (align !== "upper-left" && align !== "upper-right") {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_LAYOUT,
      message: 'Layout align must be "upper-left" or "upper-right".',
    };
  }

  const rawPadding = layout["paddingPx"];
  if (rawPadding !== undefined && !isPositiveFinite(rawPadding)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_LAYOUT,
      message: "Layout paddingPx must be a positive number.",
    };
  }
  const lineHeight = layout["lineHeight"] === undefined ? DEFAULT_LINE_HEIGHT : layout["lineHeight"];
  if (!isPositiveFinite(lineHeight) || lineHeight > 4) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_LAYOUT,
      message: "Layout lineHeight must be a positive number no greater than 4.",
    };
  }
  const explicitFontSize = layout["fontSizePx"];
  if (explicitFontSize !== undefined && !isPositiveFinite(explicitFontSize)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.INVALID_LAYOUT,
      message: "Layout fontSizePx must be a positive number.",
    };
  }

  return {
    ok: true,
    layout: {
      width: TARGET_WIDTH,
      height: TARGET_HEIGHT,
      paddingPx:
        rawPadding === undefined
          ? Math.round(TARGET_WIDTH * DEFAULT_PADDING_RATIO)
          : rawPadding,
      fontSizePx: 0, // replaced below, once the lines are known
      lineHeight,
      align,
    },
  };
}

/**
 * Derive the font size for a resolved layout and a known set of lines.
 *
 * Kept separate from resolveLayout because it depends on the text: the caller
 * resolves the layout geometry first, then this pins the type size to the
 * actual widest line so nothing overflows the canvas.
 */
export function deriveFontSize(
  layout: ResolvedLayout,
  lines: string[],
  explicitFontSize?: number,
): number {
  if (explicitFontSize !== undefined && isPositiveFinite(explicitFontSize)) {
    return Math.round(explicitFontSize);
  }
  const availableHeight = layout.height - 2 * layout.paddingPx;
  const availableWidth = layout.width - 2 * layout.paddingPx;
  const longest = Math.max(...lines.map((line) => line.length), 1);
  const byHeight = availableHeight / (lines.length * layout.lineHeight);
  const byCanvas = layout.height * MAX_FONT_SIZE_RATIO;
  const byWidth = availableWidth / (longest * ADVANCE_WIDTH_RATIO);
  const fontSize = Math.min(byCanvas, byHeight, byWidth);
  return Math.max(12, Math.round(fontSize));
}

// ---------------------------------------------------------------------------
// Request parsing
// ---------------------------------------------------------------------------

/** Parse and validate a raw request body into a renderable input. */
export function parseComposeRequest(body: unknown): ComposeValidation {
  if (typeof body !== "object" || body === null || Array.isArray(body)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.MALFORMED_REQUEST,
      message: "The request body must be a JSON object.",
    };
  }
  const record = body as Record<string, unknown>;

  const background = record["background"];
  if (typeof background !== "object" || background === null || Array.isArray(background)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.MISSING_BACKGROUND,
      message: "A background object with a PNG data URI is required.",
    };
  }
  const backgroundResult = decodeBackground((background as Record<string, unknown>)["dataUri"]);
  if (!backgroundResult.ok) return backgroundResult;

  const text = record["text"];
  if (typeof text !== "object" || text === null || Array.isArray(text)) {
    return {
      ok: false,
      code: COMPOSITOR_ERROR.MISSING_TEXT,
      message: "A text object with at least one line is required.",
    };
  }
  const textResult = validateTextLines((text as Record<string, unknown>)["lines"]);
  if (!textResult.ok) return textResult;

  const layoutResult = resolveLayout(record["layout"]);
  if (!layoutResult.ok) return layoutResult;

  const rawLayout = (record["layout"] ?? {}) as Record<string, unknown>;
  const explicitFontSize = rawLayout["fontSizePx"] as number | undefined;
  const layout: ResolvedLayout = {
    ...layoutResult.layout,
    fontSizePx: deriveFontSize(layoutResult.layout, textResult.lines, explicitFontSize),
  };

  let contentPackageId: string | null = null;
  const metadata = record["metadata"];
  if (metadata !== undefined) {
    if (typeof metadata !== "object" || metadata === null || Array.isArray(metadata)) {
      return {
        ok: false,
        code: COMPOSITOR_ERROR.MALFORMED_REQUEST,
        message: "metadata, when supplied, must be an object.",
      };
    }
    const candidate = (metadata as Record<string, unknown>)["contentPackageId"];
    if (candidate !== undefined) {
      if (typeof candidate !== "string" || candidate.length > 64) {
        return {
          ok: false,
          code: COMPOSITOR_ERROR.MALFORMED_REQUEST,
          message: "metadata.contentPackageId must be a short string.",
        };
      }
      contentPackageId = candidate;
    }
  }

  return {
    ok: true,
    input: {
      backgroundDataUri: backgroundResult.dataUri,
      backgroundBytes: backgroundResult.bytes,
      lines: textResult.lines,
      layout,
      contentPackageId,
    },
  };
}

// ---------------------------------------------------------------------------
// SVG composition
// ---------------------------------------------------------------------------

/**
 * Build the complete SVG document for a validated input.
 *
 * The background is embedded verbatim as a data URI in an `<image>` that fills
 * the canvas; a deterministic top-down scrim guarantees text contrast
 * independently of the background; and each approved line is emitted as an
 * escaped `<text>` element. Purely a string builder — no rasterizer, no I/O.
 */
export function buildSvg(input: ThumbnailComposeInput): string {
  const { width, height, paddingPx, fontSizePx, lineHeight, align } = input.layout;
  const anchorX = align === "upper-right" ? width - paddingPx : paddingPx;
  const textAnchor = align === "upper-right" ? "end" : "start";

  const parts: string[] = [];
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ` +
      `width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`,
  );

  // 1. The background, embedded unchanged. `xlink:href` is used because it is
  //    the form proven to resolve in resvg.
  parts.push(
    `<image x="0" y="0" width="${width}" height="${height}" ` +
      `preserveAspectRatio="xMidYMid slice" xlink:href="${input.backgroundDataUri}" />`,
  );

  // 2. A deterministic scrim, so contrast never depends on the background.
  parts.push(
    `<defs><linearGradient id="atlas-thumbnail-scrim" x1="0" y1="0" x2="0" y2="1">` +
      `<stop offset="0" stop-color="#070d1a" stop-opacity="0.82" />` +
      `<stop offset="0.55" stop-color="#070d1a" stop-opacity="0.34" />` +
      `<stop offset="1" stop-color="#070d1a" stop-opacity="0" />` +
      `</linearGradient></defs>` +
      `<rect x="0" y="0" width="${width}" height="${height}" fill="url(#atlas-thumbnail-scrim)" />`,
  );

  // 3. The approved text, as data.
  input.lines.forEach((line, index) => {
    const y = Math.round(paddingPx + fontSizePx * (index * lineHeight + 0.9));
    parts.push(
      `<text x="${anchorX}" y="${y}" text-anchor="${textAnchor}" ` +
        `font-family="Liberation Sans" font-weight="700" font-size="${fontSizePx}" ` +
        `fill="${TEXT_FILL}">${escapeXmlText(line)}</text>`,
    );
  });

  parts.push(`</svg>`);
  return parts.join("");
}
